name: IslandArchitect
author: ClouriaNetworkDeveloperss
authors: [Endermanbugzjfc]
api: 3.0.0
version: 1.2.5
main: Clouria\IslandArchitect\IslandArchitect
website: https://github.com/crnw-dev/IslandArchitect
softdepend: [InvCrashFix, BuilderTools, SkyBlock]
# Fuck stupid Altay don't follow the plugin dependency order to enable plugins
load: STARTUP

permissions:
  island-architect:
    default: op
    children:
      island-architect.cmd:
        description: Permission to use the "/island-architect" command
      island-architect.convert:
        description: Permission to convert a island into JSON island template file
        children:
          island.architect.convert.*:
            description: Allow a user to checkout and modify specified islands